apiVersion: v1
kind: Service
metadata:
  name: sk-random-forest-loadbalancer
spec:
  type: LoadBalancer
  ports:
  - name: api
    port: 8080
    targetPort: 8080
  - name: prometheus
    port: 8082
    targetPort: 8082
  selector:
    app: random-forest-sk