global:
  scrape_interval: 15s  # Adjust based on your needs
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'mlflow-mlserver-metrics'
    metrics_path: '/metrics'  # Default MLServer endpoint
    static_configs:
      - targets: ['mlserver:8082']  # Replace with your service name/port