apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-model
  template:
    metadata:
      labels:
        app: mlflow-model
    spec:
      containers:
      - name: mlflow-model 
        image: rhiiitech/random_forest_fromcode:latest
        ports:
        - name: api
          containerPort: 8080
        - name: metrics
          containerPort: 8082
        #volumeMounts:
        #- name: model-storage
        #  mountPath: /opt/ml/model
      #volumes:
      #- name: model-storage
      #  persistentVolumeClaim:
      #    claimName: mlflow.model.pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-model-service
spec:
  type: LoadBalancer
  selector:
    app: mlflow-model
  ports:
    - name: api
      protocol: TCP
      port: 5050
      targetPort: 8080
    - name: metrics
      protocol: TCP
      port: 5052
      targetPort: 8082